import Head from "next/head";
import "bootstrap/dist/css/bootstrap.min.css";
import "../styles/globals.css";

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Take Home Test</title>
        <meta name="description" content="Generated by Create-Next-App" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="icon/favicon.ico" />
      </Head>
      <Component {...pageProps} />;
    </>
  );
}

export default MyApp;
